/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VeilScore } from "./VeilScore";
export * as factories from "./factories";
export { VeilScore__factory } from "./factories/VeilScore__factory";
