/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VeilScoreInterface extends Interface {
  getFunction(
    nameOrSignature: "admin" | "entries" | "getEntry" | "submit"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EntrySubmitted"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "entries",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submit",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submit", data: BytesLike): Result;
}

export namespace EntrySubmittedEvent {
  export type InputTuple = [
    owner: AddressLike,
    commitment: BytesLike,
    allowed: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    commitment: string,
    allowed: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    owner: string;
    commitment: string;
    allowed: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeilScore extends BaseContract {
  connect(runner?: ContractRunner | null): VeilScore;
  waitForDeployment(): Promise<this>;

  interface: VeilScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  entries: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        owner: string;
        commitment: string;
        allowed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEntry: TypedContractMethod<
    [user: AddressLike],
    [[string, boolean, bigint]],
    "view"
  >;

  submit: TypedContractMethod<
    [commitment: BytesLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entries"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        owner: string;
        commitment: string;
        allowed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [user: AddressLike],
    [[string, boolean, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "submit"
  ): TypedContractMethod<
    [commitment: BytesLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EntrySubmitted"
  ): TypedContractEvent<
    EntrySubmittedEvent.InputTuple,
    EntrySubmittedEvent.OutputTuple,
    EntrySubmittedEvent.OutputObject
  >;

  filters: {
    "EntrySubmitted(address,bytes32,bool,uint256)": TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;
    EntrySubmitted: TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;
  };
}
